package cards;

public enum CardList {
	DORON,
	WATER_OMOTICS,
	FLAME_VIPER,
	SWORDSMAN_OF_LANDSTAR,
	THE_LEGENDARY_FISHERMAN,
	CHANGE_OF_HEART,
	TRAP_HOLE,
	MYSTICAL_SPACE_TYPHOON,
	GAIA_THE_FIERCE_KNIGHT,
	HARPIES_PET_BABY_DRAGON,
	RIGHT_LEG_OF_FORBIDDEN_ONE,
	OBELISK_THE_TOREMENTOR,
	
	
	;
}
